import { z } from 'zod'

export const AIModel = z.enum([
  'gpt-4o-2024-11-20',
  'gpt-4o-mini',
  'gpt-4',
  'gpt-4-turbo-preview',
  'gpt-4-vision-preview',
  'claude-3-haiku-20240307',
  'claude-3-5-haiku-20241022',
  'claude-3-sonnet-20240229',
  'claude-3-opus-20240229',
  'claude-3-5-sonnet-20241022',
  'claude-3-7-sonnet-20250219',
  'claude-sonnet-4-20250514',
  'claude-opus-4-20250514',
  'o1-mini-2024-09-12',
  'o1-preview',
  'o1-2024-12-17',
  'o3-2025-04-16',
  'o3-mini-2025-01-31',
  'o4-mini-2025-04-16',
  'gpt-image-1',
  'text-embedding-3-large',
  'azure/text-embedding-3-large',
  'text-embedding-3-small',
  'bedrock/anthropic.claude-3-haiku-20240307-v1:0',
  'bedrock/anthropic.claude-3-5-haiku-20241022-v1:0',
  'bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0',
  'bedrock/anthropic.claude-3-sonnet-20240229-v1:0',
  'bedrock/anthropic.claude-3-opus-20240229-v1:0',
  'gemini/gemini-1.5-pro',
  'gemini/gemini-1.5-flash',
  'gemini/gemini-exp-1114',
  'gemini/gemini-2.0-flash-exp',
  'gemini/gemini-2.0-flash',
  'gemini/gemini-2.0-pro-exp-02-05',
  'gemini-2.0-pro-exp-02-05',
  'gemini/gemini-2.0-flash-thinking-exp-01-21',
  'gemini/gemini-2.0-flash-exp-image-generation',
  'gemini/gemini-2.5-flash-preview-04-17',
  'gemini/gemini-2.5-pro-preview-03-25',
  'gemini/imagen-3.0-generate-002',
  'stability.stable-diffusion-xl-v1',
  'dall-e-3',
  'stability.stable-image-core-v1:0',
  'stability.stable-image-ultra-v1:0',
  'stability.sd3-large-v1:0',
  'vertex_ai/multimodalembedding@001',
  'bedrock/amazon.titan-embed-image-v1',
  'perplexity/sonar',
  'perplexity/sonar-reasoning-pro',
  'perplexity/sonar-reasoning',
  'perplexity/sonar-pro',
  'perplexity/sonar-deep-research',
  'moco-voice',
])
export type AIModel = z.infer<typeof AIModel>

export const FileType = z.enum([
  'application/pdf',
  'image/png',
  'image/jpeg',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'text/csv',
  'text/plain',
  'text/x-markdown',
  'application/json',
  'url',
  'text/x-python-script',
  'application/typescript',
  'text/javascript',
  'text/x-go',
  'text/x-rust',
  'text/x-java-source',
  'text/x-c',
  'text/x-csharp',
  'text/x-c++src',
  'text/html',
  'text/css',
  'text/x-ruby',
  'application/x-httpd-php',
  'application/sql',
  'text/x-sh',
  'application/octet-stream',
  'text/php',
  'text/x-ruby-script',
])

export type FileType = z.infer<typeof FileType>

export const ActionType = z.enum([
  'DEEP_SEARCH',
  'FILE_ANALYZE',
  'CREATE_TAG',
  'CREATE_ROOM_NAME',
  'CHAT',
  'BROWSE',
  'UPDATE_SUMMARY',
  'DOCUMENT_INTELLIGENCE',
  'GENERATE_ICON',
  'REGENERATE',
  'CREATE_PROPERTY',
  'ANALYZE',
  'SEARCH',
  'GENERATE_PROMPT',
  'GENERATE_IMAGE',
  'REASONING',
  'CODE_INTERPRETER',
  'AGENT',
  'TRANSCRIBE',
])

export type ActionType = z.infer<typeof ActionType>
